# Generated by Django 5.2.1 on 2025-06-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_paper_data_type_remove_paper_disease_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
