# Generated by Django 5.2.1 on 2025-06-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='field_category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='领域分类'),
        ),
    ]
