# Generated by Django 5.2.1 on 2025-06-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_paper_field_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='disease_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='technique',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='field_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
