# Generated by Django 5.2.1 on 2025-06-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_paper_disease_category_paper_technique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='model_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='模型类型'),
        ),
    ]
